import { Check, CheckCircle2, CreditCard, ExternalLink, RefreshCw, ShieldCheck, Sparkles } from 'lucide-react'
import { useState } from 'react'
import type { PlanState } from '../hooks/useSubscription'

const paymentLink = String(import.meta.env.VITE_PRO_PAYMENT_LINK || 'https://flutterwave.com/pay/xfdll6gpvuzo').trim()

export function BillingPage({ plan, userEmail, refresh }: { plan: PlanState; userName: string; userEmail: string; refresh: () => Promise<void> }) {
  const [busy,setBusy]=useState(false)
  const [error,setError]=useState('')
  const active=plan.tier==='pro'
  const checkout=()=>{
    setError('')
    if(!paymentLink){setError('The Pro payment link has not been added yet.');return}
    window.open(paymentLink,'_blank','noopener,noreferrer')
  }
  const refreshNow=async()=>{setBusy(true);setError('');try{await refresh()}catch{setError('Unable to refresh your plan right now.')}finally{setBusy(false)}}
  return <div><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><div className="eyebrow">Account plan</div><h1 className="page-title">Plan & billing</h1><p className="page-subtitle">Use MoneyCove Free or unlock Pro for $5 per month.</p></div><button className="secondary-btn" onClick={()=>void refreshNow()} disabled={busy}><RefreshCw size={16}/>{busy?'Refreshing…':'Refresh status'}</button></div>
    {error&&<div className="mt-5 rounded-2xl bg-rose-50 p-4 text-sm font-bold text-rose-700 dark:bg-rose-500/10 dark:text-rose-300">{error}</div>}
    {active&&<div className="mt-6 flex flex-col gap-4 rounded-[28px] border border-emerald-200 bg-emerald-50 p-6 text-emerald-950 dark:border-emerald-900 dark:bg-emerald-950/30 dark:text-emerald-100 sm:flex-row sm:items-center sm:justify-between"><div className="flex gap-3"><CheckCircle2 className="mt-0.5 shrink-0 text-emerald-600"/><div><div className="text-sm font-black">MoneyCove Pro is active</div><div className="mt-1 text-xs font-semibold text-emerald-700 dark:text-emerald-300">{plan.currentPeriodEnd?`Access through ${new Date(plan.currentPeriodEnd).toLocaleDateString(undefined,{day:'numeric',month:'long',year:'numeric'})}.`:'Your paid access is active.'}</div></div></div><div className="rounded-full bg-white px-3 py-1.5 text-xs font-black text-emerald-700 dark:bg-emerald-900">PRO</div></div>}
    <div className="mt-6 grid gap-5 lg:grid-cols-2"><section className={`rounded-[30px] border p-6 ${!active?'border-teal-300 ring-2 ring-teal-100 dark:ring-teal-900/30':'border-slate-200 dark:border-slate-800'}`}><div className="text-xs font-black uppercase tracking-[.18em] text-slate-400">Current base plan</div><h2 className="mt-3 text-2xl font-black text-slate-950 dark:text-white">Free</h2><div className="mt-3 text-4xl font-black text-slate-950 dark:text-white">$0</div><p className="mt-3 text-sm font-medium leading-6 text-slate-500">Everyday expense tracking and budgeting without a subscription fee.</p><div className="mt-6 grid gap-3">{['Unlimited transactions','Monthly budget','Charts and reports','Cloud account sync','CSV export'].map(x=><div key={x} className="flex gap-2 text-sm font-bold text-slate-700 dark:text-slate-300"><Check size={16} className="mt-0.5 text-teal-600"/>{x}</div>)}</div></section>
    <section className="relative overflow-hidden rounded-[30px] bg-slate-950 p-6 text-white"><div className="absolute right-5 top-5 rounded-full bg-teal-500/15 px-3 py-1 text-[10px] font-black uppercase tracking-[.16em] text-teal-300">Pro</div><Sparkles className="text-teal-300"/><h2 className="mt-4 text-2xl font-black">MoneyCove Pro</h2><div className="mt-3 flex items-end gap-2"><span className="text-4xl font-black">$5</span><span className="pb-1 text-xs font-bold text-slate-400">/ month</span></div><p className="mt-3 text-sm font-medium leading-6 text-slate-300">Unlock AI budgeting guidance and premium PDF reports.</p><div className="mt-6 grid gap-3">{['AI Money Adviser','40 AI requests each month','Premium transaction PDF','Premium budget PDF','3-page monthly financial report','Longer report trend view'].map(x=><div key={x} className="flex gap-2 text-sm font-bold text-slate-200"><Check size={16} className="mt-0.5 text-teal-300"/>{x}</div>)}</div><button className="mt-7 inline-flex min-h-11 w-full items-center justify-center gap-2 rounded-2xl bg-white px-4 text-sm font-black text-slate-950" onClick={checkout}>{active?'Renew Pro — $5':'Upgrade to Pro — $5'} <ExternalLink size={15}/></button><div className="mt-4 flex gap-2 text-[11px] font-semibold leading-5 text-slate-400"><ShieldCheck size={14} className="mt-0.5 shrink-0"/>Use the same email as your MoneyCove account when paying: <strong className="text-slate-200">{userEmail}</strong>.</div></section></div>
    <section className="panel mt-6"><div className="flex items-start gap-3"><CreditCard className="mt-0.5 shrink-0 text-indigo-600"/><div><h2 className="text-sm font-black text-slate-900 dark:text-white">After paying</h2><p className="mt-2 text-xs font-semibold leading-5 text-slate-500 dark:text-slate-400">Complete the $5 payment using the secure payment link. Once the payment is confirmed, your account is granted 30 days of Pro. Come back here and press <strong>Refresh status</strong>. Until automated payment webhooks are added, the founder control page handles activation.</p></div></div></section>
  </div>
}
