import { CheckCircle2, FileDown, Gauge, Pencil, Plus } from 'lucide-react'
import { useState } from 'react'
import { expenseCategories } from '../data/categories'
import { budgetPercentage, categoryTotals, filterByMonth, formatCurrency, getBudgetMessage } from '../utils/finance'
import { exportBudgetPdf } from '../utils/pdf'
import type { CategoryBudget, CurrencyCode, ExpenseCategory, Transaction } from '../types'

export function BudgetPage({ transactions, month, budget, setBudget, categoryBudgets, setCategoryBudgets, currency, userName, isPro, onUpgrade, notify }: { transactions: Transaction[]; month: Date; budget: number; setBudget: (v: number) => void; categoryBudgets: CategoryBudget[]; setCategoryBudgets: (v: CategoryBudget[]) => void; currency: CurrencyCode; userName: string; isPro: boolean; onUpgrade: () => void; notify: (m:string)=>void }) {
  const monthTx = filterByMonth(transactions, month)
  const spent = monthTx.filter(t => t.type === 'expense').reduce((s,t)=>s+t.amount,0)
  const percent = budgetPercentage(spent,budget)
  const remaining = budget > 0 ? budget-spent : 0
  const totals = categoryTotals(monthTx)
  const [editing, setEditing] = useState(false)
  const [draft, setDraft] = useState(String(budget))
  const [cat, setCat] = useState<ExpenseCategory>('Food')
  const [catLimit, setCatLimit] = useState('')
  const saveBudget = () => { const n=Number(draft); if(n>0){setBudget(n);setEditing(false);notify('Monthly budget updated')} }
  const saveCat = () => { const n=Number(catLimit); if(!(n>0)) return; setCategoryBudgets([...categoryBudgets.filter(b=>b.category!==cat),{category:cat,limit:n}]); setCatLimit(''); notify('Category budget updated') }
  const exportPdf = () => exportBudgetPdf({ transactions, month, budget, categoryBudgets, currency, userName })
  return <div><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><div className="eyebrow">Spending guardrails</div><h1 className="page-title">Budget</h1><p className="page-subtitle">Set your monthly target and keep important categories in check.</p></div><button className="secondary-btn" onClick={()=>isPro?exportPdf():onUpgrade()}><FileDown size={17}/> Export Budget PDF {!isPro&&<span className="rounded-full bg-slate-100 px-1.5 py-0.5 text-[9px] font-black text-slate-400 dark:bg-slate-800">PRO</span>}</button></div>
    <div className="mt-6 grid gap-6 xl:grid-cols-[1.2fr_.8fr]"><section className="panel overflow-hidden"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><div className="eyebrow">Monthly budget</div>{editing ? <div className="mt-2 flex max-w-sm gap-2"><input className="field-input" inputMode="numeric" value={draft} onChange={(e)=>setDraft(e.target.value.replace(/\D/g,''))}/><button className="primary-btn" onClick={saveBudget}>Save</button></div> : <div className="mt-1 text-4xl font-black tracking-tight text-slate-900 dark:text-white">{formatCurrency(budget,currency)}</div>}</div><button className="secondary-btn" onClick={()=>setEditing(!editing)}><Pencil size={15}/> Edit</button></div>
      <div className="relative mx-auto mt-8 grid aspect-square max-w-[290px] place-items-center rounded-full" style={{background:`conic-gradient(${percent>100?'#e11d48':percent>80?'#f59e0b':'#0f766e'} ${budget>0?Math.min(percent,100)*3.6:0}deg, rgba(148,163,184,.16) 0deg)`}}><div className="grid size-[78%] place-items-center rounded-full bg-white text-center shadow-inner dark:bg-slate-900"><div><Gauge className="mx-auto text-teal-600" size={24}/><div className="mt-2 text-4xl font-black text-slate-900 dark:text-white">{budget>0?`${Math.round(percent)}%`:'—'}</div><div className="text-xs font-bold text-slate-400">{budget>0?'used':'set a budget'}</div></div></div></div>
      <div className="mt-6 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-slate-50 p-4 dark:bg-slate-800/60"><div className="text-xs font-bold text-slate-400">Spent</div><div className="mt-1 text-lg font-extrabold text-slate-800 dark:text-slate-100">{formatCurrency(spent,currency)}</div></div><div className="rounded-2xl bg-slate-50 p-4 dark:bg-slate-800/60"><div className="text-xs font-bold text-slate-400">Remaining</div><div className={`mt-1 text-lg font-extrabold ${remaining < 0 ? 'text-rose-600' : 'text-slate-800 dark:text-slate-100'}`}>{formatCurrency(Math.abs(remaining),currency)}{remaining<0?' over':''}</div></div></div>
      <div className="mt-4 flex gap-3 rounded-2xl border border-teal-100 bg-teal-50 p-4 text-sm font-semibold leading-6 text-teal-900 dark:border-teal-900/50 dark:bg-teal-950/30 dark:text-teal-200"><CheckCircle2 className="mt-0.5 shrink-0" size={18}/>{budget>0?getBudgetMessage(percent):'Set a monthly budget to measure how much of your target you have used.'}</div>
    </section>
    <section className="panel"><div className="panel-head"><div><div className="eyebrow">Optional controls</div><h2 className="section-title">Category budgets</h2></div></div><div className="space-y-4">{categoryBudgets.map((b)=>{const used=totals[b.category]??0; const pct=budgetPercentage(used,b.limit); return <div key={b.category}><div className="flex items-end justify-between gap-2"><div><div className="text-sm font-extrabold text-slate-800 dark:text-slate-100">{b.category}</div><div className="mt-1 text-xs font-semibold text-slate-400">{formatCurrency(used,currency)} of {formatCurrency(b.limit,currency)}</div></div><div className="text-xs font-extrabold text-slate-500">{Math.round(pct)}%</div></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-100 dark:bg-slate-800"><div className={`h-full rounded-full ${pct>100?'bg-rose-500':pct>80?'bg-amber-500':'bg-indigo-500'}`} style={{width:`${Math.min(pct,100)}%`}}/></div></div>})}</div>
      <div className="mt-6 border-t border-slate-100 pt-5 dark:border-slate-800"><div className="mb-2 text-xs font-extrabold uppercase tracking-[.14em] text-slate-400">Add or update</div><div className="grid gap-2 sm:grid-cols-[1fr_1fr_auto]"><select className="filter-select" value={cat} onChange={e=>setCat(e.target.value as ExpenseCategory)}>{expenseCategories.map(c=><option key={c}>{c}</option>)}</select><input className="field-input" inputMode="numeric" value={catLimit} onChange={e=>setCatLimit(e.target.value.replace(/\D/g,''))} placeholder="Limit"/><button className="primary-btn" onClick={saveCat}><Plus size={15}/> Set</button></div></div>
    </section></div>
  </div>
}
