import { ArrowDownRight, ArrowUpRight, FileDown, PiggyBank, Sparkles } from 'lucide-react'
import { IncomeExpenseBars, SpendingDonut, SpendingTrend } from '../components/Charts'
import { categoryTotals, filterByMonth, formatCurrency, getTotals, monthOverMonth, topCategory } from '../utils/finance'
import { exportFinancialReportPdf, exportMonthlyExpensePdf } from '../utils/pdf'
import type { CategoryBudget, CurrencyCode, Transaction } from '../types'

export function ReportsPage({ transactions, month, budget, categoryBudgets, currency, userName, isPro, onUpgrade }: { transactions: Transaction[]; month: Date; budget: number; categoryBudgets: CategoryBudget[]; currency: CurrencyCode; userName: string; isPro: boolean; onUpgrade: () => void }) {
  const current=filterByMonth(transactions,month); const prevMonth=new Date(month.getFullYear(),month.getMonth()-1,1); const previous=filterByMonth(transactions,prevMonth); const totals=getTotals(current); const prevTotals=getTotals(previous)
  const cats=categoryTotals(current); const pie=Object.entries(cats).map(([name,value])=>({name,value})).sort((a,b)=>b.value-a.value)
  const monthly = (isPro ? [-11,-10,-9,-8,-7,-6,-5,-4,-3,-2,-1,0] : [-4,-3,-2,-1,0]).map((offset)=>{const d=new Date(month.getFullYear(),month.getMonth()+offset,1); const t=getTotals(filterByMonth(transactions,d)); return {month:d.toLocaleDateString(undefined,{month:'short'}), income:t.income, expenses:t.expenses}})
  const days=Array.from({length:new Date(month.getFullYear(),month.getMonth()+1,0).getDate()},(_,i)=>i+1); let running=0; const trend=days.map(day=>{running+=current.filter(t=>t.type==='expense'&&Number(t.date.slice(-2))===day).reduce((s,t)=>s+t.amount,0); return {label:String(day),value:running}})
  const biggest=topCategory(current); const expenseChange=monthOverMonth(totals.expenses,prevTotals.expenses)
  const insights=[biggest.category?`${biggest.category} is your biggest spending category this month.`:'Add expenses to unlock category insights.', `You spent ${formatCurrency(Math.abs(totals.expenses-prevTotals.expenses),currency)} ${expenseChange>=0?'more':'less'} than last month.`, `You have used ${budget?Math.round((totals.expenses/budget)*100):0}% of your monthly budget.`, `You saved ${Math.max(0,totals.savingsRate).toFixed(1)}% of your income.`]
  const reportContext={ transactions, month, budget, categoryBudgets, currency, userName }; const exportPdf = () => exportFinancialReportPdf(reportContext); const exportFreePdf=()=>exportMonthlyExpensePdf(reportContext)
  return <div><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><div className="eyebrow">Money intelligence</div><h1 className="page-title">Reports</h1><p className="page-subtitle">Clear trends, savings insights and premium monthly reporting.</p></div><div className="flex flex-wrap gap-2"><button className="secondary-btn" onClick={exportFreePdf}><FileDown size={17}/> Monthly Expense PDF <span className="rounded-full bg-teal-50 px-1.5 py-0.5 text-[9px] font-black text-teal-700 dark:bg-teal-500/10 dark:text-teal-300">FREE</span></button><button className="primary-btn" onClick={()=>isPro?exportPdf():onUpgrade()}><FileDown size={17}/> Full Financial PDF {!isPro&&<span className="rounded-full bg-white/15 px-1.5 py-0.5 text-[9px] font-black">PRO</span>}</button></div></div>
    <div className="mt-6 grid gap-4 sm:grid-cols-3"><div className="metric-card"><div className="metric-icon bg-emerald-50 text-emerald-700 dark:bg-emerald-500/10"><PiggyBank size={20}/></div><p className="metric-label">Savings</p><p className="metric-value">{formatCurrency(totals.savings,currency)}</p><p className="mt-2 text-xs font-bold text-slate-400">{totals.savingsRate.toFixed(1)}% of income</p></div><div className="metric-card"><div className="metric-icon bg-indigo-50 text-indigo-700 dark:bg-indigo-500/10">{expenseChange>0?<ArrowUpRight size={20}/>:<ArrowDownRight size={20}/>}</div><p className="metric-label">Expense change</p><p className="metric-value">{Math.abs(expenseChange).toFixed(1)}%</p><p className="mt-2 text-xs font-bold text-slate-400">vs previous month</p></div><div className="metric-card"><div className="metric-icon bg-amber-50 text-amber-700 dark:bg-amber-500/10"><Sparkles size={20}/></div><p className="metric-label">Budget used</p><p className="metric-value">{budget?Math.round(totals.expenses/budget*100):0}%</p><p className="mt-2 text-xs font-bold text-slate-400">of this month’s target</p></div></div>
    <div className="mt-6 grid gap-6 xl:grid-cols-2"><section className="panel"><div className="panel-head"><div><div className="eyebrow">Breakdown</div><h2 className="section-title">Spending by category</h2></div></div>{pie.length?<SpendingDonut data={pie} currency={currency}/>:<div className="grid h-64 place-items-center text-sm font-semibold text-slate-400">No expenses for this month.</div>}</section><section className="panel"><div className="panel-head"><div><div className="eyebrow">Comparison</div><h2 className="section-title">Income vs expenses</h2></div></div><IncomeExpenseBars data={monthly} currency={currency}/></section><section className="panel xl:col-span-2"><div className="panel-head"><div><div className="eyebrow">Momentum</div><h2 className="section-title">Spending trend</h2></div></div><SpendingTrend data={trend} currency={currency}/></section></div>
    <section className="panel mt-6"><div className="panel-head"><div><div className="eyebrow">Calculated locally</div><h2 className="section-title">Financial insights</h2></div></div><div className="grid gap-3 md:grid-cols-2">{insights.map((text,i)=><div key={i} className="flex gap-3 rounded-2xl bg-slate-50 p-4 dark:bg-slate-800/60"><div className="grid size-9 shrink-0 place-items-center rounded-xl bg-white text-teal-600 shadow-sm dark:bg-slate-900"><Sparkles size={16}/></div><p className="text-sm font-semibold leading-6 text-slate-600 dark:text-slate-300">{text}</p></div>)}</div></section>
  </div>
}
