import { useEffect, useState, type FormEvent, type ReactNode } from 'react'
import { ArrowRight, CheckCircle2, Eye, EyeOff, LockKeyhole, Mail, ShieldCheck, Sparkles, UserRound } from 'lucide-react'
import { Logo } from '../components/Logo'
import { SEO } from '../components/SEO'
import { useAuth } from '../context/AuthContext'
import { requireSupabase } from '../lib/supabase'
import { APP_VERSION } from '../version'

function AuthShell({ eyebrow, title, subtitle, children }: { eyebrow:string; title:string; subtitle:string; children:ReactNode }){
  return <main className="relative min-h-dvh overflow-hidden bg-slate-950 text-white"><div className="pointer-events-none absolute inset-0"><div className="absolute -left-24 -top-24 size-96 rounded-full bg-teal-500/20 blur-3xl"/><div className="absolute -bottom-28 -right-20 size-[30rem] rounded-full bg-indigo-500/20 blur-3xl"/><div className="absolute inset-0 bg-[radial-gradient(circle_at_center,rgba(255,255,255,.055)_1px,transparent_1px)] bg-[size:24px_24px] opacity-40"/></div><div className="relative mx-auto grid min-h-dvh max-w-[1380px] lg:grid-cols-[1.05fr_.95fr]"><section className="hidden flex-col justify-between p-10 lg:flex xl:p-14"><a href="/" className="w-fit rounded-2xl bg-white px-4 py-3 shadow-2xl shadow-black/20"><Logo/></a><div className="max-w-xl py-16"><div className="mb-5 inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/5 px-3 py-2 text-xs font-extrabold text-teal-200"><Sparkles size={15}/> Personal finance, simplified</div><h1 className="text-5xl font-black leading-[1.02] tracking-[-0.05em] xl:text-6xl">Know where your money goes.</h1><p className="mt-6 max-w-lg text-base font-medium leading-7 text-slate-300">Track income, expenses and budgets from one calm dashboard, then unlock premium reports and AI guidance when you need more.</p><div className="mt-10 grid max-w-lg gap-3 sm:grid-cols-2"><div className="rounded-3xl border border-white/10 bg-white/[0.06] p-5"><ShieldCheck className="text-teal-300" size={22}/><div className="mt-5 text-sm font-extrabold">Real account access</div><div className="mt-1 text-xs font-semibold leading-5 text-slate-400">Your session can be remembered securely between visits.</div></div><div className="rounded-3xl border border-white/10 bg-white/[0.06] p-5"><UserRound className="text-indigo-300" size={22}/><div className="mt-5 text-sm font-extrabold">Your finance workspace</div><div className="mt-1 text-xs font-semibold leading-5 text-slate-400">Saved finance data belongs to your signed-in account.</div></div></div></div><div className="text-xs font-semibold text-slate-500">MoneyCove v{APP_VERSION} · A Nile AI Solutions product</div></section><section className="flex min-h-dvh items-center justify-center px-4 py-8 sm:px-8 lg:px-10"><div className="w-full max-w-[500px] rounded-[32px] border border-white/10 bg-white p-6 text-slate-900 shadow-2xl shadow-black/30 sm:p-8 lg:p-10"><a href="/" className="mb-8 block lg:hidden"><Logo/></a><div className="inline-flex size-12 items-center justify-center rounded-2xl bg-gradient-to-br from-teal-600 to-indigo-600 text-white shadow-lg shadow-teal-600/20"><LockKeyhole size={21}/></div><div className="mt-5 text-[10px] font-black uppercase tracking-[.20em] text-teal-700">{eyebrow}</div><h2 className="mt-1 text-3xl font-black tracking-[-0.035em] text-slate-950">{title}</h2><p className="mt-2 text-sm font-medium leading-6 text-slate-500">{subtitle}</p>{children}</div></section></div></main>
}

function PasswordInput({ value, onChange, placeholder='Password', autoComplete='current-password' }: { value:string; onChange:(v:string)=>void; placeholder?:string; autoComplete?:string }){
  const [show,setShow]=useState(false)
  return <div className="relative"><input className="field-input pr-12" type={show?'text':'password'} value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} autoComplete={autoComplete}/><button type="button" className="absolute right-1.5 top-1/2 grid size-9 -translate-y-1/2 place-items-center rounded-xl text-slate-400 transition hover:bg-slate-100 hover:text-slate-700" onClick={()=>setShow(v=>!v)} aria-label={show?'Hide password':'Show password'}>{show?<EyeOff size={18}/>:<Eye size={18}/>}</button></div>
}

function ConfigWarning(){return <div className="mt-6 rounded-2xl bg-amber-50 p-4 text-xs font-bold leading-5 text-amber-800">Cloud authentication has not been configured for this deployment yet. Add the Supabase environment variables from <code>.env.example</code>.</div>}

function safeNextPath(value: string | null) {
  if (!value || !value.startsWith('/') || value.startsWith('//')) return '/app#/dashboard'
  return value
}

export function LoginPage(){
  const { user, configured }=useAuth(); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [busy,setBusy]=useState(false); const [error,setError]=useState('')
  const params=new URLSearchParams(window.location.search); const next=safeNextPath(params.get('next'))
  useEffect(()=>{ if(user) window.location.replace(next) },[user,next])
  const submit=async(e:FormEvent)=>{e.preventDefault(); setBusy(true);setError('');try{const client=requireSupabase();const {error:authError}=await client.auth.signInWithPassword({email:email.trim(),password});if(authError)throw authError;window.location.replace(next)}catch(err){setError(err instanceof Error?err.message:'Unable to sign in.')}finally{setBusy(false)}}
  return <><SEO title="Sign in to MoneyCove" description="Sign in to your MoneyCove account." path="/login" robots="noindex,nofollow"/><AuthShell eyebrow="Welcome back" title="Sign in to MoneyCove" subtitle="Continue to your saved transactions, budgets and reports.">{!configured&&<ConfigWarning/>}<form className="mt-7 space-y-5" onSubmit={submit}><label className="block"><span className="field-label">Email address</span><input className="field-input" type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com" autoComplete="email" required/></label><label className="block"><div className="mb-2 flex items-center justify-between"><span className="field-label mb-0">Password</span><a href="/forgot-password" className="text-xs font-extrabold text-teal-700">Forgot password?</a></div><PasswordInput value={password} onChange={setPassword}/></label>{error&&<div className="rounded-2xl bg-rose-50 px-4 py-3 text-xs font-bold leading-5 text-rose-700">{error}</div>}<button className="primary-btn w-full" type="submit" disabled={busy||!configured}>{busy?'Signing in…':'Sign in'} {!busy&&<ArrowRight size={17}/>}</button></form><p className="mt-6 text-center text-xs font-semibold text-slate-500">New to MoneyCove? <a className="font-black text-teal-700" href="/signup">Create a free account</a></p></AuthShell></>
}

export function SignupPage(){
  const { user, configured }=useAuth(); const [name,setName]=useState(''); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [busy,setBusy]=useState(false); const [error,setError]=useState('')
  const wantsPro=new URLSearchParams(window.location.search).get('plan')==='pro'
  useEffect(()=>{ if(user) window.location.replace(wantsPro?'/app#/billing':'/app#/dashboard') },[user,wantsPro])
  const submit=async(e:FormEvent)=>{e.preventDefault();if(name.trim().length<2){setError('Enter your name.');return}if(password.length<8){setError('Use at least 8 characters for your password.');return}setBusy(true);setError('');try{const client=requireSupabase();const cleanEmail=email.trim().toLowerCase();const signupUrl='https://dpmajonvvhopjnupgfpq.supabase.co/functions/v1/pesapilot-signup';const response=await fetch(signupUrl,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:name.trim(),email:cleanEmail,password})});let payload:any={};try{payload=await response.json()}catch{}if(!response.ok)throw new Error(payload?.error||'Unable to create account.');const {error:signInError}=await client.auth.signInWithPassword({email:cleanEmail,password});if(signInError)throw signInError;window.location.replace(wantsPro?'/app#/billing':'/app#/dashboard')}catch(err){setError(err instanceof Error?err.message:'Unable to create account.')}finally{setBusy(false)}}
  return <><SEO title="Create a MoneyCove Account" description="Create your free MoneyCove expense tracking and budget account." path="/signup" robots="noindex,nofollow"/><AuthShell eyebrow="Start free" title="Create your MoneyCove account" subtitle={wantsPro?'Create your account and continue straight to the $5 Pro upgrade.':'Start free. No email verification step — your account opens immediately.'}>{!configured&&<ConfigWarning/>}<form className="mt-7 space-y-5" onSubmit={submit}><label className="block"><span className="field-label">Your name</span><input className="field-input" value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Titus" autoComplete="name" required/></label><label className="block"><span className="field-label">Email address</span><input className="field-input" type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com" autoComplete="email" required/></label><label className="block"><span className="field-label">Password</span><PasswordInput value={password} onChange={setPassword} placeholder="At least 8 characters" autoComplete="new-password"/></label><div className="rounded-2xl bg-teal-50 px-4 py-3 text-xs font-bold leading-5 text-teal-800">Your account is ready immediately after signup. We do not ask you to verify the email before using MoneyCove.</div>{error&&<div className="rounded-2xl bg-rose-50 px-4 py-3 text-xs font-bold leading-5 text-rose-700">{error}</div>}<button className="primary-btn w-full" type="submit" disabled={busy||!configured}>{busy?'Creating account…':'Create free account'} {!busy&&<ArrowRight size={17}/>}</button></form><p className="mt-6 text-center text-xs font-semibold text-slate-500">Already have an account? <a className="font-black text-teal-700" href="/login">Sign in</a></p></AuthShell></>
}

export function ForgotPasswordPage(){
  const {configured}=useAuth();const [email,setEmail]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [sent,setSent]=useState(false)
  const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{const client=requireSupabase();const {error:resetError}=await client.auth.resetPasswordForEmail(email.trim(),{redirectTo:`${window.location.origin}/reset-password`});if(resetError)throw resetError;setSent(true)}catch(err){setError(err instanceof Error?err.message:'Unable to send reset email.')}finally{setBusy(false)}}
  return <><SEO title="Reset MoneyCove Password" description="Request a password reset for your MoneyCove account." path="/forgot-password" robots="noindex,nofollow"/><AuthShell eyebrow="Account recovery" title="Reset your password" subtitle="Enter the email address on your MoneyCove account.">{!configured&&<ConfigWarning/>}{sent?<div className="mt-7 rounded-3xl bg-emerald-50 p-6 text-center"><Mail className="mx-auto text-emerald-700"/><h3 className="mt-3 text-lg font-black">Check your email</h3><p className="mt-2 text-sm font-medium leading-6 text-slate-600">If an account exists for that email, you’ll receive a password reset link.</p></div>:<form className="mt-7 space-y-5" onSubmit={submit}><label className="block"><span className="field-label">Email address</span><input className="field-input" type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email" required/></label>{error&&<div className="rounded-2xl bg-rose-50 px-4 py-3 text-xs font-bold text-rose-700">{error}</div>}<button className="primary-btn w-full" disabled={busy||!configured}>{busy?'Sending…':'Send reset link'}</button></form>}<p className="mt-6 text-center text-xs font-semibold text-slate-500"><a href="/login" className="font-black text-teal-700">Back to sign in</a></p></AuthShell></>
}

export function ResetPasswordPage(){
  const {user,configured}=useAuth();const [password,setPassword]=useState('');const [confirm,setConfirm]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [done,setDone]=useState(false)
  const submit=async(e:FormEvent)=>{e.preventDefault();if(password.length<8){setError('Use at least 8 characters.');return}if(password!==confirm){setError('Passwords do not match.');return}setBusy(true);setError('');try{const client=requireSupabase();const {error:updateError}=await client.auth.updateUser({password});if(updateError)throw updateError;await client.auth.refreshSession();setDone(true)}catch(err){setError(err instanceof Error?err.message:'Unable to update password.')}finally{setBusy(false)}}
  return <><SEO title="Choose a New MoneyCove Password" description="Choose a new password for your MoneyCove account." path="/reset-password" robots="noindex,nofollow"/><AuthShell eyebrow="Account recovery" title="Choose a new password" subtitle="Set a new password for your MoneyCove account.">{!configured&&<ConfigWarning/>}{done?<div className="mt-7 rounded-3xl bg-emerald-50 p-6 text-center"><CheckCircle2 className="mx-auto text-emerald-700"/><h3 className="mt-3 text-lg font-black">Password updated</h3><a href="/app#/dashboard" className="primary-btn mt-5">Continue to MoneyCove</a></div>:!user?<div className="mt-7 rounded-2xl bg-amber-50 p-4 text-xs font-bold leading-5 text-amber-800">Open this page from the password-reset email so MoneyCove can verify the recovery session.</div>:<form className="mt-7 space-y-5" onSubmit={submit}><label className="block"><span className="field-label">New password</span><PasswordInput value={password} onChange={setPassword} placeholder="At least 8 characters" autoComplete="new-password"/></label><label className="block"><span className="field-label">Confirm password</span><PasswordInput value={confirm} onChange={setConfirm} placeholder="Repeat password" autoComplete="new-password"/></label>{error&&<div className="rounded-2xl bg-rose-50 px-4 py-3 text-xs font-bold text-rose-700">{error}</div>}<button className="primary-btn w-full" disabled={busy}>{busy?'Updating…':'Update password'}</button></form>}</AuthShell></>
}
