import { ArrowRight, CalendarDays, Clock } from 'lucide-react'
import { SEO } from '../components/SEO'
import { blogPosts, getBlogPost } from '../data/blogPosts'
import { PublicLayout } from './PublicLayout'

export function BlogIndexPage(){
  return <PublicLayout><SEO title="MoneyCove Blog — Practical Budgeting & Expense Tracking" description="Practical guides on expense tracking, budgeting, irregular income and reducing overspending." path="/blog"/>
    <main className="mx-auto max-w-[1100px] px-4 py-16 sm:px-6"><div className="max-w-3xl"><div className="eyebrow">MoneyCove guides</div><h1 className="mt-3 text-5xl font-black tracking-[-.05em]">Make clearer money decisions, one habit at a time.</h1><p className="mt-5 text-base font-medium leading-7 text-slate-500">Short, practical articles designed to make budgeting and expense tracking easier to keep up with.</p></div><div className="mt-12 grid gap-5 md:grid-cols-2">{blogPosts.map(post=><article key={post.slug} className="group rounded-[28px] border border-slate-200 p-6 transition hover:-translate-y-1 hover:shadow-xl hover:shadow-slate-950/5"><div className="flex items-center gap-3 text-[11px] font-extrabold text-slate-400"><span className="rounded-full bg-teal-50 px-2.5 py-1 text-teal-700">{post.category}</span><span>{post.readTime}</span></div><h2 className="mt-5 text-2xl font-black tracking-[-.03em]">{post.title}</h2><p className="mt-3 text-sm font-medium leading-6 text-slate-500">{post.excerpt}</p><a href={`/blog/${post.slug}`} className="mt-6 inline-flex items-center gap-2 text-sm font-black text-teal-700">Read guide <ArrowRight size={16}/></a></article>)}</div></main>
  </PublicLayout>
}

export function BlogArticlePage({ slug }: { slug: string }){
  const post=getBlogPost(slug)
  if(!post) return <PublicLayout><main className="mx-auto max-w-3xl px-4 py-24 text-center"><h1 className="text-4xl font-black">Article not found</h1><a href="/blog" className="primary-btn mt-6">Back to blog</a></main></PublicLayout>
  const articleLd={ '@context':'https://schema.org','@type':'Article',headline:post.title,description:post.description,datePublished:post.published,dateModified:post.published,author:{'@type':'Organization',name:'Nile AI Solutions'},publisher:{'@type':'Organization',name:'Nile AI Solutions'},mainEntityOfPage:`https://moneycove.nileai.solutions/blog/${post.slug}` }
  return <PublicLayout><SEO title={`${post.title} | MoneyCove`} description={post.description} path={`/blog/${post.slug}`} type="article" jsonLd={articleLd}/><main className="mx-auto max-w-[820px] px-4 py-14 sm:px-6"><a href="/blog" className="text-sm font-black text-teal-700">← All guides</a><div className="mt-8"><div className="eyebrow">{post.category}</div><h1 className="mt-3 text-4xl font-black leading-tight tracking-[-.045em] sm:text-5xl">{post.title}</h1><p className="mt-5 text-lg font-medium leading-8 text-slate-500">{post.excerpt}</p><div className="mt-6 flex flex-wrap gap-4 text-xs font-bold text-slate-400"><span className="flex items-center gap-1.5"><CalendarDays size={14}/>{new Date(post.published).toLocaleDateString('en',{day:'numeric',month:'long',year:'numeric'})}</span><span className="flex items-center gap-1.5"><Clock size={14}/>{post.readTime}</span></div></div><article className="mt-10 border-t border-slate-200 pt-9">{post.sections.map((section,i)=><section key={i} className="mb-9">{section.heading&&<h2 className="mb-3 text-2xl font-black tracking-[-.03em]">{section.heading}</h2>}{section.paragraphs.map((p,j)=><p key={j} className="mb-4 text-[16px] font-medium leading-8 text-slate-600">{p}</p>)}{section.bullets&&<ul className="my-5 grid gap-2 pl-5 text-[15px] font-semibold leading-7 text-slate-600">{section.bullets.map(x=><li key={x} className="list-disc">{x}</li>)}</ul>}</section>)}</article><div className="rounded-[28px] bg-slate-950 p-7 text-white"><h2 className="text-2xl font-black">Put the ideas into practice with MoneyCove.</h2><p className="mt-2 text-sm font-medium leading-6 text-slate-300">Create a free account to track transactions, build a monthly budget and see your money in one dashboard.</p><a href="/signup" className="mt-5 inline-flex min-h-11 items-center justify-center rounded-2xl bg-white px-5 text-sm font-black text-slate-950">Start free</a></div></main></PublicLayout>
}
