import { Mail, ShieldCheck, Sparkles } from 'lucide-react'
import { SEO } from '../components/SEO'
import { PublicLayout } from './PublicLayout'

export function AboutPage(){return <PublicLayout><SEO title="About MoneyCove" description="Learn why MoneyCove was built and how it helps people track spending and plan budgets more clearly." path="/about"/><main className="mx-auto max-w-[900px] px-4 py-16 sm:px-6"><div className="eyebrow">About</div><h1 className="mt-3 text-5xl font-black tracking-[-.05em]">Personal finance software should feel calm, not complicated.</h1><div className="mt-8 grid gap-6 text-base font-medium leading-8 text-slate-600"><p>MoneyCove is an expense tracker and budget planner built by Nile AI Solutions, with real accounts, cloud sync, premium reports and optional AI budgeting guidance.</p><p>The product focuses on everyday visibility: what came in, what went out, how much remains, which categories are growing and whether spending is still within the plan.</p><p>MoneyCove is not designed to trade investments or tell users what securities to buy. Its AI adviser is intentionally focused on budgeting, spending patterns and personal-finance organization.</p></div><div className="mt-10 grid gap-4 sm:grid-cols-3">{[['Simple','Record money without maintaining formulas.'],['Clear','See the month in a dashboard you can understand quickly.'],['Useful','Turn records into practical decisions, reports and budget guidance.']].map(([t,d])=><div key={t} className="rounded-3xl bg-slate-50 p-5"><Sparkles className="text-teal-700" size={19}/><h2 className="mt-4 text-lg font-black">{t}</h2><p className="mt-2 text-sm font-medium leading-6 text-slate-500">{d}</p></div>)}</div></main></PublicLayout>}

export function ContactPage(){return <PublicLayout><SEO title="Contact MoneyCove" description="Contact the MoneyCove team at Nile AI Solutions." path="/contact"/><main className="mx-auto max-w-[900px] px-4 py-16 sm:px-6"><div className="rounded-[36px] bg-slate-950 p-8 text-white sm:p-10"><Mail className="text-teal-300"/><div className="mt-5 text-xs font-black uppercase tracking-[.18em] text-teal-300">Contact</div><h1 className="mt-2 text-4xl font-black tracking-[-.04em]">Questions about MoneyCove?</h1><p className="mt-4 max-w-2xl text-sm font-medium leading-7 text-slate-300">For product support, billing questions, partnerships or feedback, email the Nile AI Solutions team.</p><a className="mt-7 inline-flex min-h-11 items-center justify-center rounded-2xl bg-white px-5 text-sm font-black text-slate-950" href="mailto:hello@nileai.solutions">hello@nileai.solutions</a></div></main></PublicLayout>}

export function PrivacyPage(){return <PublicLayout><SEO title="MoneyCove Privacy Policy" description="Read how MoneyCove handles account, finance, AI and payment data." path="/privacy"/><Legal title="Privacy Policy" updated="19 August 2026" sections={[
['Account information','MoneyCove uses Supabase authentication for account access. Your email address, account metadata and authentication session are processed so you can sign in and return to your account.'],
['Finance data','Transactions, budgets, settings and related app state are stored in the MoneyCove database under your user account. Row-level security is used so authenticated users can access their own finance state. A local browser cache may also be kept to improve resilience and speed.'],
['AI Adviser','The AI Adviser is optional and available to Pro users. When you submit a question, MoneyCove sends the question and a structured financial summary needed to answer it to the configured AI provider. The application does not send your password or payment credentials to the AI provider.'],
['Payments','Pro checkout opens a hosted Flutterwave payment link. MoneyCove does not store card or mobile-money credentials in the browser. During the current launch phase, the founder confirms the payment reference and grants 30 days of Pro from the private Founder page.'],
['Security and retention','Server-only credentials such as service-role, AI and payment keys are kept in deployment environment variables. You should use a strong password and protect access to your devices.'],
['Contact','Privacy questions can be sent to hello@nileai.solutions.']
]}/></PublicLayout>}

export function TermsPage(){return <PublicLayout><SEO title="MoneyCove Terms of Use" description="Read the terms that apply when using MoneyCove Free and Pro." path="/terms"/><Legal title="Terms of Use" updated="19 August 2026" sections={[
['Using MoneyCove','You may use MoneyCove to record and organize personal finance information, create budgets and generate reports. You are responsible for the accuracy of the information you enter and for keeping your account credentials secure.'],
['Free and Pro plans','The Free plan may be used without a subscription fee. Pro features require an active paid period. Prices and included limits may change in the future, but changes should be shown before a new purchase.'],
['AI guidance','MoneyCove AI provides general budgeting and spending guidance based on information in the app. It is not a substitute for professional investment, tax, legal, accounting or credit advice. You remain responsible for financial decisions.'],
['Payments','A completed Pro payment grants the paid access period shown at checkout. Refunds, reversals and failed payments may remove or shorten paid access where appropriate.'],
['Availability','We aim to keep MoneyCove available and reliable, but software, hosting, third-party authentication, AI services and payment networks can experience interruptions.'],
['Acceptable use','Do not attempt to abuse usage limits, access another user’s data, attack the service, reverse-engineer secrets or use the platform for unlawful activity.'],
['Contact','Questions about these terms can be sent to hello@nileai.solutions.']
]}/></PublicLayout>}

function Legal({title,updated,sections}:{title:string;updated:string;sections:[string,string][]}){return <main className="mx-auto max-w-[820px] px-4 py-16 sm:px-6"><div className="flex items-center gap-2 text-xs font-black uppercase tracking-[.18em] text-teal-700"><ShieldCheck size={16}/> Legal</div><h1 className="mt-3 text-5xl font-black tracking-[-.05em]">{title}</h1><p className="mt-3 text-sm font-semibold text-slate-400">Last updated: {updated}</p><div className="mt-10 grid gap-8">{sections.map(([h,p])=><section key={h}><h2 className="text-xl font-black">{h}</h2><p className="mt-2 text-sm font-medium leading-7 text-slate-600">{p}</p></section>)}</div></main>}
