import { Check, Sparkles } from 'lucide-react'
import { SEO } from '../components/SEO'
import { useAuth } from '../context/AuthContext'
import { PublicLayout } from './PublicLayout'

export function PricingPage(){
  const {user}=useAuth()
  const productLd={ '@context':'https://schema.org','@type':'Product',name:'MoneyCove Pro',description:'Premium MoneyCove plan with AI budgeting guidance and PDF reports',offers:{'@type':'Offer',price:'5',priceCurrency:'USD',availability:'https://schema.org/InStock'} }
  return <PublicLayout><SEO title="MoneyCove Pricing — Free or $5/Month Pro" description="Use MoneyCove Free for everyday expense tracking and budgets, or upgrade to Pro for $5/month to unlock AI guidance and premium PDF reports." path="/pricing" jsonLd={productLd}/>
    <main className="mx-auto max-w-[1100px] px-4 py-16 sm:px-6 lg:py-20"><div className="mx-auto max-w-3xl text-center"><div className="eyebrow">Simple pricing</div><h1 className="mt-3 text-5xl font-black tracking-[-.05em]">Free for the essentials. $5 when you want more.</h1><p className="mt-5 text-base font-medium leading-7 text-slate-500">No crowded plan matrix. Start with a useful free account and upgrade to one clear Pro plan.</p></div><div className="mx-auto mt-12 grid max-w-4xl gap-5 lg:grid-cols-2">
      <section className="rounded-[32px] border border-slate-200 p-7"><div className="text-sm font-black">Free</div><div className="mt-4 flex items-end gap-2"><span className="text-5xl font-black tracking-[-.05em]">$0</span><span className="pb-1 text-sm font-bold text-slate-400">forever</span></div><p className="mt-4 text-sm font-medium leading-6 text-slate-500">For everyday tracking, budgeting and visibility.</p><a href={user?'/app#/dashboard':'/signup'} className="secondary-btn mt-7 w-full">{user?'Open MoneyCove':'Start free'}</a><div className="mt-7 grid gap-3">{['Unlimited income & expense tracking','Monthly budget','Category spending breakdown','Dashboard charts & reports','Cloud account sync','CSV export','Monthly expense PDF','Light, dark & system themes','Installable PWA'].map(x=><div key={x} className="flex gap-2 text-sm font-bold text-slate-700"><Check size={17} className="mt-0.5 shrink-0 text-teal-700"/>{x}</div>)}</div></section>
      <section className="relative overflow-hidden rounded-[32px] bg-slate-950 p-7 text-white"><div className="absolute right-5 top-5 rounded-full bg-teal-500/15 px-3 py-1 text-[10px] font-black uppercase tracking-[.16em] text-teal-300">Pro</div><Sparkles className="text-teal-300"/><div className="mt-5 text-sm font-black">MoneyCove Pro</div><div className="mt-4 flex items-end gap-2"><span className="text-5xl font-black tracking-[-.05em]">$5</span><span className="pb-1 text-sm font-bold text-slate-400">/ month</span></div><p className="mt-4 text-sm font-medium leading-6 text-slate-300">For deeper reports and AI-powered budgeting guidance.</p><a href={user?'/app#/billing':'/signup?plan=pro'} className="mt-7 inline-flex min-h-11 w-full items-center justify-center rounded-2xl bg-white px-4 text-sm font-black text-slate-950">{user?'Upgrade to Pro':'Start with Pro'}</a><div className="mt-7 grid gap-3">{['Everything in Free','AI Money Adviser','Up to 40 AI adviser requests per month','Premium transaction PDF','Premium budget PDF','3-page monthly financial report','Longer report trend view','Pro status inside the app'].map(x=><div key={x} className="flex gap-2 text-sm font-bold text-slate-200"><Check size={17} className="mt-0.5 shrink-0 text-teal-300"/>{x}</div>)}</div></section>
    </div><div className="mx-auto mt-8 max-w-4xl rounded-2xl bg-slate-50 p-5 text-sm font-medium leading-6 text-slate-500"><strong className="text-slate-800">How Pro activation works:</strong> pay $5 through the secure payment link using the same email as your MoneyCove account. Once payment is confirmed, 30 days of Pro access is activated.</div></main>
  </PublicLayout>
}
