import { BarChart3, Brain, CalendarDays, CreditCard, Crown, LogOut, Settings, UserRound, X } from 'lucide-react'
import type { PageKey } from '../hooks/useHashPage'

export function MoreSheet({ open, onClose, setPage, userName, userEmail, isPro, isFounder, onLogout }: { open: boolean; onClose: () => void; setPage: (p: PageKey) => void; userName: string; userEmail:string; isPro:boolean; isFounder:boolean; onLogout: () => void }) {
  if (!open) return null
  const go = (page: PageKey) => { setPage(page); onClose() }
  const logout = () => { onClose(); onLogout() }
  return <div className="modal-backdrop lg:hidden" onClick={onClose}><div className="dialog-card pb-[max(24px,env(safe-area-inset-bottom))]" onClick={(e)=>e.stopPropagation()}><div className="flex items-center justify-between"><div><div className="eyebrow">More</div><h2 className="section-title">Explore MoneyCove</h2></div><button className="icon-btn" onClick={onClose}><X size={18}/></button></div><div className="mt-5 flex items-center gap-3 rounded-2xl bg-slate-50 p-3 dark:bg-slate-800/60"><span className="settings-icon bg-gradient-to-br from-teal-600 to-indigo-600 text-white"><UserRound size={18}/></span><span className="min-w-0"><strong className="block truncate text-sm font-extrabold text-slate-800 dark:text-slate-100">{userName}</strong><small className="mt-0.5 block truncate text-xs font-semibold text-slate-400">{isPro?'MoneyCove Pro':userEmail}</small></span></div><div className="mt-3 grid gap-3"><button className="settings-action" onClick={()=>go('reports')}><span className="settings-icon text-indigo-600"><BarChart3 size={18}/></span><span><strong>Reports & insights</strong><small>See category charts, trends and savings insights.</small></span></button><button className="settings-action" onClick={()=>go('ai')}><span className="settings-icon text-teal-700"><Brain size={18}/></span><span><strong>AI Adviser {isPro?'':'· Pro'}</strong><small>Ask budgeting questions using your own financial summary.</small></span></button><button className="settings-action" onClick={()=>go('billing')}><span className="settings-icon text-indigo-600"><CreditCard size={18}/></span><span><strong>Plan & billing</strong><small>View Free or Pro status and manage your paid access.</small></span></button><button className="settings-action" onClick={()=>go('calendar')}><span className="settings-icon text-rose-500"><CalendarDays size={18}/></span><span><strong>Calendar</strong><small>Browse money activity by day, month or year.</small></span></button><button className="settings-action" onClick={()=>go('settings')}><span className="settings-icon text-teal-700"><Settings size={18}/></span><span><strong>Settings</strong><small>Currency, theme, export and account controls.</small></span></button>{isFounder&&<button className="settings-action" onClick={()=>go('founder')}><span className="settings-icon text-amber-600"><Crown size={18}/></span><span><strong>Founder control</strong><small>Manage users, $5 payments and Pro access.</small></span></button>}<button className="settings-action group" onClick={logout}><span className="settings-icon text-rose-500 group-hover:bg-rose-50 dark:group-hover:bg-rose-500/10"><LogOut size={18}/></span><span><strong className="text-rose-600">Log out</strong><small>Sign out of this device. Your cloud data remains in your account.</small></span></button></div></div></div>
}
